#!/bin/bash
# GameMetrics Pro - Essential Deployment Scripts
# 
# This folder contains the minimal set of scripts needed for deployment.
# Use these scripts in order:

echo "═══════════════════════════════════════════════════════════════"
echo "  GameMetrics Pro - Deployment Scripts Reference"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 AVAILABLE SCRIPTS:"
echo ""
echo "1️⃣  INFRASTRUCTURE (One-time setup)"
echo "   bash deploy-infra-only.sh"
echo "   └─ Deploys: AWS infrastructure, EKS cluster, RDS, Redis, Kafka"
echo "   └─ Output: .infra-output.env (infrastructure details)"
echo "   └─ Run first!"
echo ""
echo "2️⃣  APPLICATIONS (Deploy to Kubernetes)"
echo "   bash deploy-apps-to-k8s.sh"
echo "   └─ Deploys: event-ingestion service to K8s cluster"
echo "   └─ Uses: .infra-output.env from step 1"
echo "   └─ Run after infrastructure is ready"
echo ""
echo "3️⃣  BUILD & PUSH (Local image building)"
echo "   bash build-push-ecr.sh"
echo "   └─ Builds Docker image locally"
echo "   └─ Pushes to ECR repository"
echo "   └─ Use: For manual local builds before pushing to GitHub"
echo ""
echo "4️⃣  STATUS CHECK (Monitor cluster)"
echo "   bash check-status.sh"
echo "   └─ Shows cluster, pod, and service status"
echo "   └─ Use: To monitor deployment health"
echo ""
echo "5️⃣  SECRETS (Sync AWS Secrets Manager)"
echo "   bash update-secrets-from-aws.sh"
echo "   └─ Called automatically by deploy-infra-only.sh"
echo "   └─ Use: Manually if secrets need refresh"
echo ""
echo "📚 REFERENCE (Don't execute, just read)"
echo "   cat commands.sh"
echo "   └─ Useful kubectl and AWS commands"
echo "   └─ cat DEPLOYMENT.md for full documentation"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🚀 TYPICAL WORKFLOW:"
echo ""
echo "  1. First time setup:"
echo "     bash deploy-infra-only.sh       # ~10-15 min"
echo "     bash deploy-apps-to-k8s.sh      # ~2-3 min"
echo ""
echo "  2. For daily development (automated via CI/CD):"
echo "     git push origin develop         # Triggers GitHub Actions"
echo "                                     # Auto-builds, pushes, deploys"
echo ""
echo "  3. Manual local testing:"
echo "     bash build-push-ecr.sh          # Build locally"
echo "     bash check-status.sh            # Monitor deployment"
echo ""
echo "═══════════════════════════════════════════════════════════════"
